// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ApplyTitlePanel: typeof import('./src/components/ApplyTitlePanel/index.vue')['default']
    AreaSelect: typeof import('./src/components/AreaSelect/index.vue')['default']
    Chart: typeof import('./src/components/Charts/Chart.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
    MainTitlePanel: typeof import('./src/components/MainTitlePanel/index.vue')['default']
    PeripheralQuery: typeof import('./src/components/PeripheralQuery/index.vue')['default']
    PeripheralStatistics: typeof import('./src/components/PeripheralStatistics/index.vue')['default']
    PipeDetailPanel: typeof import('./src/components/PipeDetailPanel/index.vue')['default']
    PlotComparison: typeof import('./src/components/PlotComparison/index.vue')['default']
    PlotDetailPanel: typeof import('./src/components/PlotDetailPanel/index.vue')['default']
    PlotUsageChart: typeof import('./src/components/PeripheralStatistics/components/plot-usage-chart/index.vue')['default']
    PopulationStatChart: typeof import('./src/components/PeripheralStatistics/components/population-stat-chart/index.vue')['default']
    ResultPanel: typeof import('./src/components/ResultPanel/index.vue')['default']
    SubPanel: typeof import('./src/components/SubPanel/index.vue')['default']
    SubTitlePanel: typeof import('./src/components/SubTitlePanel/index.vue')['default']
  }
}

export { }
